export const CUBOID_REQUEST = 'CUBOID_REQUEST'
export const CUBOID_SUCCESS = 'CUBOID_SUCCESS'
export const CUBOID_FAIL = 'CUBOID_FAIL'
export const CUBOID_COMPUTE_INTERNAL_REQUEST = 'CUBOID_COMPUTE_INTERNAL_REQUEST'
export const CUBOID_COMPUTE_INTERNAL_SUCCESS = 'CUBOID_COMPUTE_INTERNAL_SUCCESS'
export const CUBOID_COMPUTE_INTERNAL_FAIL = 'CUBOID_COMPUTE_INTERNAL_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
